export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const CHANGE_DELIVERY_ADDRESS = 'CHANGE_DELIVERY_ADDRESS'; 
export const CHANGE_CHECKOUT_PAYMENT = 'CHANGE_CHECKOUT_PAYMENT'; 
export const RESET_CART = 'RESET_CART';